[package]
name = "test-sentry"
version = "0.1.0"
authors = ["Quentin de Quelen <quentin@dequelen.me>"]
edition = "2018"

[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
tide = "0.6.0"
sentry = "0.18.0"
